name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: fmt -verify
        run: ./v fmt -verify symlinker/

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: Build symlinker
        run: ./v -prod symlinker/
      - name: Run tests
        run: ./v test symlinker
