name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up V
        uses: nocturlab/setup-vlang-action@v1
        with:
          v-version: master
        id: v
      - name: Verify code formatting
        run: |
          v fmt -verify sl_cli.v sl_cli_test.v
          cd linker
          v fmt -verify linker.v linker_test.v
          cd ..
      - name: Build symlinker
        run: v -cg -prod .
      - name: Run tests
        run: v test .
