name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: fmt -verify
        run: |
          cd symlinker
          ../v fmt -verify main.v
          ../v fmt -verify main_test.v
          ../v fmt -verify linker.v
          ../v fmt -verify linker_test.v

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: Build symlinker
        run: |
          cd symlinker
          ../v -prod .
      - name: Run tests
        run: |
          cd symlinker
          ../v test .
