name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: fmt -verify
        run: ./v fmt -verify symlinker/

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: Run tests
        run: ./v -W test symlinker

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Build V
        run: make
      - name: Checkout symlinker
        uses: actions/checkout@v2
        with:
            path: symlinker
      - name: Build symlinker
        run: ./v -prod symlinker/
